name: Maven Package upon a push
on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - master
      - 1.*
      - develop
      - MOSIP*
      - release*

jobs:
  build-maven-esignet-mock-services:
    uses: mosip/kattu/.github/workflows/maven-build.yml@master
    with:
      SERVICE_LOCATION: ./
      BUILD_ARTIFACT: esignet-mock-services
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  publish_to_nexus:
    if: "${{ !contains(github.ref, 'master') && github.event_name != 'pull_request' }}"
    needs: build-maven-esignet-mock-services
    uses: mosip/kattu/.github/workflows/maven-publish-to-nexus.yml@master
    with:
      SERVICE_LOCATION: ./
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_URL: ${{ secrets.RELEASE_URL }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  sonar_analysis:
    needs: build-maven-esignet-mock-services
    if: "${{  github.event_name != 'pull_request' }}"
    uses: mosip/kattu/.github/workflows/maven-sonar-analysis.yml@master
    with:
      SERVICE_LOCATION: ./
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ORG_KEY: ${{ secrets.ORG_KEY }}
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build-dockers:
    needs: build-maven-esignet-mock-services
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'mock-identity-system'
            SERVICE_NAME: 'mock-identity-system'
            BUILD_ARTIFACT: 'esignet-mock-services'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
          password: ${{ secrets.ACTOR_DOCKER_HUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.SERVICE_LOCATION }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:latest
            ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:${{ github.sha }}
            ${{ secrets.RELEASE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:latest
            ${{ secrets.RELEASE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:${{ github.sha }}

  build-dockers-mock:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'mock-relying-party-service'
            SERVICE_NAME: 'mock-relying-party-service'
          - SERVICE_LOCATION: 'mock-relying-party-ui'
            SERVICE_NAME: 'mock-relying-party-ui'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
          password: ${{ secrets.ACTOR_DOCKER_HUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.SERVICE_LOCATION }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:latest
            ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:${{ github.sha }}
            ${{ secrets.RELEASE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:latest
            ${{ secrets.RELEASE_DOCKER_HUB }}/${{ matrix.SERVICE_NAME }}:${{ github.sha }}
